server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka3000.com:3000/eureka/
  instance:
    instance-id: zuul-server-2
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

spring:
  application:
    name: zuul-server #此实例注册到eureka服务端的name

zuul:
  prefix: /api
  ignored-services: "*"
  strip-prefix: false
  routes:
    mypower:
      serviceId: server-power
      path: /power/**