server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka3000.com:3000/eureka/
  instance:
    instance-id: zuul-server-1 #这里是eureka中显示的服务实例名称
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

spring:
  application:
    name: zuul-server

zuul:
  prefix: /api
  strip-prefix: false #带前缀
  ignored-services: "*"
  routes:
    mypower:
      serviceId: server-power
      path: /power/**